### ISSUE TITLE
Discuss symmetric vs asymmetric JWT signatures

### ISSUE THREAD

**Issue by Legion2** [VirtualProgrammingLab/viplab-websocket-api#11]
Currently the implementation uses asymmetric JWT signatures generated with the "RS512" singing algorithm. This enables the websocket-api to accept signed messages from many different services each with it own private key. But it also introduces complex private/public key management for both applications.

Symmetric JWT singing does not require the complex asymmetric keys and work with a simple string shared secret. But the private key is shared between all external services and the websocket-api.

An ADR should be created to document the decision about the use of symmetric or asymmetric JWT signatures.

**Comment by pascalseeland** [comment]
I don't think a shared secret will work for the following usecase:  In the current viplab setup, we have two different universities sharing one common backend infrastructure. Using a shared secret would require all participating clients to share a secret.
